options(verbose=TRUE)
expect_equal(testRcppAttributePackage::test_no_attributes(list("{A}"), FALSE),list("{A}", FALSE)) 
expect_equal(testRcppAttributePackage::test_signature(),list("{A}", TRUE))
expect_equal(testRcppAttributePackage::test_rng_false_signature_invisible_true(),list("{A}", TRUE))
expect_equal(testRcppAttributePackage::test_rng_false(list("{A}"), FALSE),list("{A}", FALSE)) 
expect_equal(testRcppAttributePackage::test_rng_true(list("{A}"), FALSE),list("{A}", FALSE))
expect_equal(testRcppAttributePackage::test_rng_true_signature(),list("{A}", TRUE))
expect_equal(testRcppAttributePackage::test_invisible_true_rng_true(list("{A}"), FALSE),list("{A}", FALSE))
expect_equal(testRcppAttributePackage::test_invisible_true(list("{A}"), FALSE),list("{A}", FALSE))
expect_equal(testRcppAttributePackage::test_invisible_true_signature(),list("{A}", TRUE))
options(verbose=FALSE)