\documentclass[10pt]{article}
%\VignetteIndexEntry{Rcpp-unitTests}
\usepackage{vmargin}
\setmargrb{0.75in}{0.75in}{0.75in}{0.75in}

\usepackage[colorlinks]{hyperref}
\author{Dirk Eddelbuettel \and Romain Fran\c{c}ois}
\title{Rcpp : Unit testing results}
\begin{document}
\maketitle

\begin{verbatim}
<<echo=F,results=tex>>=
writeLines( readLines( "unitTests-results/Rcpp-unitTests.txt" ) ) 
@
\end{verbatim}

\end{document}
