# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_no_attributes <- function(x, verbose) {
    .Call(`_testRcppAttributePackage_test_no_attributes`, x, verbose)
}

test_signature <- function(x = list("{A}", "B"), verbose = getOption("verbose")) {
    .Call(`_testRcppAttributePackage_test_signature`, x, verbose)
}

test_rng_false_signature_invisible_true <- function(x = list("{A}", "B"), verbose = getOption("verbose")) {
    invisible(.Call(`_testRcppAttributePackage_test_rng_false_signature_invisible_true`, x, verbose))
}

test_rng_false <- function(x, verbose) {
    .Call(`_testRcppAttributePackage_test_rng_false`, x, verbose)
}

test_rng_true <- function(x, verbose) {
    .Call(`_testRcppAttributePackage_test_rng_true`, x, verbose)
}

test_rng_true_signature <- function(x = list("{A}", "B"), verbose = getOption("verbose")) {
    .Call(`_testRcppAttributePackage_test_rng_true_signature`, x, verbose)
}

test_invisible_true_rng_true <- function(x, verbose) {
    invisible(.Call(`_testRcppAttributePackage_test_invisible_true_rng_true`, x, verbose))
}

test_invisible_true <- function(x, verbose) {
    invisible(.Call(`_testRcppAttributePackage_test_invisible_true`, x, verbose))
}

test_invisible_true_signature <- function(x = list("{A}", "B"), verbose = getOption("verbose")) {
    invisible(.Call(`_testRcppAttributePackage_test_invisible_true_signature`, x, verbose))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_testRcppAttributePackage_RcppExport_registerCCallable', PACKAGE = 'testRcppAttributePackage')
})
